### ISSUE TITLE
BFS traversal doesn't seem to properly account for undirected edges

### ISSUE THREAD

**Issue by ohxh** [graphology/graphology-traversal#2]
Accidentally posted in the wrong repo before (https://github.com/graphology/graphology/issues/197).

Unless I'm misunderstanding the API for adding edges, BFS traversal only seems to look at undirected edges in one direction.

In a decently dense random graph (where we expect a large part to be one connected component), a BFS traversal from a node inside the component doesn't find the entire component. If you double up all the edges in the opposite direction, the value is as expected.

There's not a lot of detail in this description, but I imagine for a maintainer of this project this would be a quick fix-- just swap out `forEachOutboundNeighbor` or change its implementation. I'll try to upload a working reproduction later.

**Comment by Yomguithereal** [comment]
@ohxh `forEachOutboundNeighbor` means we iterate on both directed out edges and undirected ones from the current node, so I am not sure to understand what went wrong here. I am afraid I will need a reproduction to pinpoint the problem. Can you also double-check that you are using a proper undirected graph or that you added your edges using undirected version of the methods if your graph is mixed?

**Comment by ohxh** [comment]
Ahhh nvm I had confused myself creating the graph, and my edges were indeed directed. Thanks for the help, and for maintaining such a useful repo
